### ISSUE TITLE
Does not apply color to text layers

### ISSUE THREAD

**Issue by andrejilderda** [colesperks/QuickColor#6]
Nice plugin Cole! It doesn't seem to work on text layers on Sketch 40.3 though. Are you aware of that? I don't see any errors in the console either.

Thanks for the plugin!

**Comment by colesperks** [comment]
@ajilderda I really appreciate your feedback. Currently the plugin only supports changing the color of shapes. But I plan to hopefully release the a text color change in a later version :) Thanks for creating the issue 👍

**Comment by colesperks** [comment]
@ajilderda The plugin now works with Sketch 41 and also applies to text layers thanks to @Ashung 🙂

**Comment by andrejilderda** [comment]
Great, thanks Cole!
